/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCandidateDialog: typeof import('./src/components/jobs/AddCandidateDialog.vue')['default']
    ApplicantProfileDialog: typeof import('./src/components/jobs/ApplicantProfileDialog.vue')['default']
    AssignInterviewDialog: typeof import('./src/components/jobs/AssignInterviewDialog.vue')['default']
    BulkMoveDialog: typeof import('./src/components/jobs/BulkMoveDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendEmailDialog: typeof import('./src/components/jobs/SendEmailDialog.vue')['default']
  }
}
